backend:
  name: git-gateway
  branch: main
local_backend: false
media_folder: public/uploads
public_folder: /uploads
collections:
  - name: verbs
    label: Verbs
    folder: content/verbs
    create: true
    slug: '{{lemma.transliteration}}'
    format: yaml
    fields:
      - label: ID - infinitive
        name: id
        widget: string
      - label: Category
        name: categoryId
        widget: relation
        collection: categories
        search_fields:
          - name
          - slug
        value_field: slug
        display_fields:
          - name
        required: false
      - label: Reflexive
        name: reflexive
        widget: boolean
        default: false
        hint: Check if this verb is reflexive. 'זיך/zikh' will be automatically inserted in conjugations (e.g., 'איך האָב זיך געלערנט'). Do NOT include 'זיך/zikh' in the fields below.
      - label: Infinitive
        name: lemma
        widget: object
        fields:
          - label: Yiddish
            name: yiddish
            widget: string
          - label: Transliteration (YIVO)
            name: transliteration
            widget: string
      - label: Meaning
        name: meaning
        widget: object
        required: false
        fields:
          - label: English
            name: english
            widget: string
      - label: Auxiliary
        name: auxiliary
        widget: select
        options:
          - hobn
          - zayn
        required: true
      - label: Conjugation
        name: conjugation
        widget: object
        fields:
          - label: Present Tense
            name: present
            widget: object
            required: true
            fields:
              - label: ich
                name: ich
                widget: object
                fields:
                  - label: Yiddish
                    name: yiddish
                    widget: string
                  - label: Transliteration
                    name: transliteration
                    widget: string
              - label: du
                name: du
                widget: object
                fields:
                  - label: Yiddish
                    name: yiddish
                    widget: string
                  - label: Transliteration
                    name: transliteration
                    widget: string
              - label: er / zi / es
                name: er_zi_es
                widget: object
                fields:
                  - label: Yiddish
                    name: yiddish
                    widget: string
                  - label: Transliteration
                    name: transliteration
                    widget: string
              - label: mir
                name: mir
                widget: object
                fields:
                  - label: Yiddish
                    name: yiddish
                    widget: string
                  - label: Transliteration
                    name: transliteration
                    widget: string
              - label: ir
                name: ir
                widget: object
                fields:
                  - label: Yiddish
                    name: yiddish
                    widget: string
                  - label: Transliteration
                    name: transliteration
                    widget: string
              - label: zey
                name: zey
                widget: object
                fields:
                  - label: Yiddish
                    name: yiddish
                    widget: string
                  - label: Transliteration
                    name: transliteration
                    widget: string
          - label: Past Participle
            name: past_participle
            widget: object
            required: true
            fields:
              - label: Yiddish
                name: yiddish
                widget: string
              - label: Transliteration
                name: transliteration
                widget: string
      - label: Search
        name: search
        widget: object
        required: false
        fields:
          - label: Yiddish
            name: yiddish
            widget: list
          - label: Transliteration
            name: transliteration
            widget: list
      - label: Notes
        name: notes
        widget: list
        required: false
  - name: categories
    label: Categories
    folder: content/categories
    files:
      - label: Simple
        name: simple
        file: content/categories/simple.yml
        fields:
          - label: Name
            name: name
            widget: string
          - label: Slug
            name: slug
            widget: string
          - label: Content
            name: content
            widget: markdown
  - name: pages
    label: Pages
    files:
      - label: About
        name: about
        file: content/pages/about.yml
        fields:
          - label: Title
            name: title
            widget: string
          - label: Slug
            name: slug
            widget: string
          - label: Content
            name: content
            widget: markdown
